CREATE DATABASE shortdb;
CREATE USER gopher WITH ENCRYPTED PASSWORD 'short';

GRANT ALL PRIVILEGES ON DATABASE shortdb TO gopher;

\connect shortdb;

CREATE TABLE links (
  slug CHAR(5) PRIMARY KEY NOT NULL,
  url VARCHAR(200) NOT NULL,
  createdAt TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO gopher;
