version: "3.4"

services:
  app:
    build:
      context: .
      target: dev
    working_dir: /usr/src/app
    container_name: go-url-shortener
    depends_on:
     - postgres
    tty: true
    ports:
      - 8080:8080
    environment:
      - SSH_AUTH_SOCK=/tmp/ssh_auth.sock
    extra_hosts:
      - dockerhost:${DOCKERHOST:-172.17.0.1}
    volumes:
      - .:/usr/src/app
      - $SSH_AUTH_SOCK:/tmp/ssh_auth.sock

  postgres:
    image: postgres:12-alpine
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data/pgdata
      - ./docker/postgres:/docker-entrypoint-initdb.d
      - .:/app
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
