port: 8080
database:
  connectURL: ""
  host: postgres
  port: 5432
  name: shortdb
  user: gopher
  pass: short
  sslMode: disable
cache:
  connectURL: ""
  host: redis
  port: 6379

  linksTTLSeconds: 21600
